
DROP PROCEDURE [dbo].[QUERY1_1]
GO
DROP PROCEDURE [dbo].[QUERY1_2]
GO
DROP PROCEDURE [dbo].[QUERY1_3]
GO
DROP PROCEDURE [dbo].[QUERY2_1]
GO
DROP PROCEDURE [dbo].[QUERY2_2]
GO
DROP PROCEDURE [dbo].[QUERY2_3]
GO
DROP PROCEDURE [dbo].[QUERY2_4]
GO
DROP PROCEDURE [dbo].[QUERY3]
GO
DROP PROCEDURE [dbo].[QUERY4_1]
GO
DROP PROCEDURE [dbo].[QUERY4_2]
GO
DROP PROCEDURE [dbo].[QUERY4_3]
GO
DROP PROCEDURE [dbo].[QUERY5]
GO
DROP PROCEDURE [dbo].[QUERY6_1]
GO
DROP PROCEDURE [dbo].[QUERY6_2]
GO
DROP PROCEDURE [dbo].[QUERY7]
GO
DROP PROCEDURE [dbo].[QUERY8]
GO
DROP PROCEDURE [dbo].[QUERY9]
GO
DROP PROCEDURE [dbo].[QUERY10]
GO